project:
  type: website
  output-dir: docs

  
website:
  title: "Karar's Quarto Website"
  navbar:
   background: primary
   search: true

   left:
      - text: "Home"
        file: index.qmd
      - about.qmd

     #left:
    #  - href: index.qmd
    #    text: Home


format:
  html:
    theme: slate
    css: styles.css
    toc: true
editor: visual

